# Generated by Django 5.1.5 on 2025-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='empName',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
