# Generated by Django 5.1.5 on 2025-01-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=122)),
                ('lastName', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('language', models.CharField(max_length=50, null=True)),
                ('education', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
